// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbgwGcFkZy3Iw6MGJ0yhZSyWuMLqG_w5Q',
    appId: '1:357296382847:web:d5ffd38a8cbcb90d14f04a',
    messagingSenderId: '357296382847',
    projectId: 'zuperr-apk',
    authDomain: 'zuperr-apk.firebaseapp.com',
    storageBucket: 'zuperr-apk.firebasestorage.app',
    measurementId: 'G-GYDF32MM2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS5m2s_alh51LiGOV2LHx-owaxn4Y8e7s',
    appId: '1:357296382847:android:c5110f17b0c600cf14f04a',
    messagingSenderId: '357296382847',
    projectId: 'zuperr-apk',
    storageBucket: 'zuperr-apk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDB18RpUNSNAlLnmSmELq1T0NPMU0k0xw',
    appId: '1:357296382847:ios:a589b0dbd46a611c14f04a',
    messagingSenderId: '357296382847',
    projectId: 'zuperr-apk',
    storageBucket: 'zuperr-apk.firebasestorage.app',
    androidClientId: '357296382847-4cqopf0iji8nudd1j7ugjpsglevqgjlm.apps.googleusercontent.com',
    iosClientId: '357296382847-ks60jpo0aiskj0vleg2ils7q97teg49d.apps.googleusercontent.com',
    iosBundleId: 'com.example.zuperr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDB18RpUNSNAlLnmSmELq1T0NPMU0k0xw',
    appId: '1:357296382847:ios:a589b0dbd46a611c14f04a',
    messagingSenderId: '357296382847',
    projectId: 'zuperr-apk',
    storageBucket: 'zuperr-apk.firebasestorage.app',
    androidClientId: '357296382847-4cqopf0iji8nudd1j7ugjpsglevqgjlm.apps.googleusercontent.com',
    iosClientId: '357296382847-ks60jpo0aiskj0vleg2ils7q97teg49d.apps.googleusercontent.com',
    iosBundleId: 'com.example.zuperr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbgwGcFkZy3Iw6MGJ0yhZSyWuMLqG_w5Q',
    appId: '1:357296382847:web:60a8c2c13c30d7b114f04a',
    messagingSenderId: '357296382847',
    projectId: 'zuperr-apk',
    authDomain: 'zuperr-apk.firebaseapp.com',
    storageBucket: 'zuperr-apk.firebasestorage.app',
    measurementId: 'G-94JYSLMTD6',
  );
}
